require_relative 'operands/abstract_base.rb'
require_relative 'operands/number.rb'
require_relative 'operands/symbol.rb'
require_relative 'operands/reserved_label.rb'
require_relative 'operands/segment.rb'
